# Generated by Django 5.1.2 on 2024-10-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_customer_user_last_seen_alter_customer_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type_message',
            field=models.CharField(choices=[('disconnect', 'disconnect'), ('connect', 'connect'), ('seen', 'seen')], default='disconnect', max_length=20),
        ),
    ]
